-- DCE Dispatch Adapter Type Declarations
-- This file contains ONLY type declarations for the Dispatch adapter interface.
-- Vendor-neutral: Does not reference any specific CAD/MDT implementation.
-- No runtime logic, no business logic.

--- @class IDispatchAdapter
--- Dispatch Adapter Interface: Integrates with external CAD/MDT systems.
--- Adapters translate DCE dispatch calls into external API calls.
--- Must be implemented by ERS, Sonoran CAD, PS-Dispatch, or custom adapters.
---@field Name string Adapter identifier
---@field Priority number Adapter priority (used for selection when multiple available)
---@field IsAvailable fun(self:IDispatchAdapter):boolean Check if adapter can connect to external system
---@field CreateCall fun(self:IDispatchAdapter, data:DispatchCallSummary):nil Create a new dispatch call
---@field UpdateCall fun(self:IDispatchAdapter, data:DispatchCallSummary):nil Update an existing call
---@field ResolveCall fun(self:IDispatchAdapter, data:DispatchCallSummary):nil Resolve a call
---@field CancelCall fun(self:IDispatchAdapter, data:DispatchCallSummary):nil Cancel a call
---@field GetDiagnostics fun(self:IDispatchAdapter):table Get adapter health and status information
---@field HealthCheck fun(self:IDispatchAdapter):boolean Check if adapter connection is healthy