-- DCE Framework Core Type Declarations
-- This file contains ONLY type declarations for the DCE framework runtime API.
-- The framework API is used internally by DCE and provides core infrastructure.
-- No runtime logic, no business logic, no plugin registration.

---@class DCEFramework
--- The main DCE framework API exposed via the global DCE table.
--- This interface is for internal DCE use, not plugin SDK.
--- Service Registry API
---@field GetService fun(name:string):table|nil
---@field HasService fun(name:string):boolean
---@field GetServiceOrThrow fun(name:string):table
---@field RegisterService fun(name:string, service:table, options?:table):boolean
---@field UnregisterService fun(name:string):boolean
--- Event Bus API
---@field Emit fun(eventName:string, payload:table):nil
---@field On fun(eventName:string, handlerFn:function):number|nil
---@field Once fun(eventName:string, handlerFn:function):number|nil
---@field Off fun(eventName:string, handlerId:number):nil
--- Scheduler API
---@field Schedule fun(taskName:string, intervalMs:number, callback:function, options?:table):boolean
---@field ScheduleNow fun(taskName:string):boolean
--- Logger convenience
---@field Log fun(module:string, level:string, message:string, ...:any):nil
--- Version convenience (Sprint 1.7)
---@field GetVersion fun():string
--- Ready state query (Sprint 1.10.2)
---@field IsReady fun():boolean
--- Internal ready state flag (private, set after boot pipeline completes)
---@field _ready boolean
--- Plugin SDK functions
---@field RegisterPlugin fun(manifest:table):(boolean, string|nil)
---@field LoadConfig fun(path:string):table|nil
---@field ValidateConfig fun(config:table, schema:table):boolean
---@field RegisterOrganization fun(orgDataTable:table):(boolean, string|nil)
---@field RegisterDispatchAdapter fun(adapterTable:table):boolean
---@field RegisterEvidenceAdapter fun(adapterTable:table):boolean
---@field RegisterMDTAdapter fun(adapterTable:table):boolean
---@field RegisterBehavior fun(behaviorDataTable:table):boolean
---@field RegisterEscalationChain fun(escalationSchemaTable:table):boolean
---@type DCEFramework
DCE = nil
